config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'profiles/edit'
  get 'profiles/update'

  get 'friends/destroy'
  devise_for :users, :controllers => { registrations: "my_registrations", omniauth_callbacks: 'users/omniauth_callbacks' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"
  resources :users, only: [:show]
  get 'profile', to: 'users#show'
  resources :friend_requests
  resources :friends, only: [:index, :destroy]
  resources :posts
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resource :profile, only: %i[edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true

  has_many :likes, as: :likeable
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :user_id, uniqueness: { scope: :friend_id, message: "A friend request is already pending"}

  def accept
    user.friends << friend
    destroy
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  after_create :create_inverse_relationship
  after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validate :not_self

  def create_inverse_relationship
    friend.friendships.create(friend: user) if friend.friendships.where(friend: user).blank?
    puts 'test'
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end

  private

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  validates :user_id, uniqueness: { scope: %i[likeable_id likeable_type]}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes, as: :likeable
  has_many :comments, as: :commentable

  scope :posts_by_user, ->(user) { where(user: user)}
  scope :posts_by_friends, ->(user) { where(user: user.friends )}

  scope :timeline_for, ->(user) { posts_by_user(user).or(posts_by_friends(user)) }
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :name,        presence: true
  validates :description, presence: true, length: { maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_default_profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github]
  
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :posts, dependent: :destroy

  has_many :likes
  has_many :comments

  has_one :profile, dependent: :destroy

  def create_default_profile
    create_profile(name: email, description: "Nothing here yet!")
  end

  def remove_friend(friend)
    current_user.friends.destroy(friend)
  end

  def name
    if profile
      profile.name || email
    else
      email
    end
  end

  def is_friend_or_pending_friend(user)
    pending_friends.include?(user) || friends.include?(user) || self == user
  end
  
  def is_friends_with?(friend)
    pending_friends.include?(friend)
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    puts data
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
        user = User.create(
           email: data['email'],
           password: Devise.friendly_token[0,20]
        )
    end
    user
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.save
    redirect_back fallback_location: root_path
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: :destroy
  
  def index
    @friends = current_user.friends
  end

  def destroy
    current_user.remove_friend(@friend)
    head :no_content
  end

  def set_friend
    @friend = current_user.friends.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.new(like_params)

    @like.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def like_params
    params.require(:like).permit(:likeable_id, :likeable_type)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.timeline_for(current_user)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ edit update ]

  def edit
  end

  def update
    if @profile.update(profile_params)
      puts "help"
      redirect_to user_path(current_user), notice: "Post was successfully updated."
    else
      puts "help"
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:name, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = params[:id] ? User.find(params[:id]) : current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url_for(user, opts = {})
    size = opts[:size || 32]

    hash = Digest::MD5.hexdigest(user.email.downcase)
    "https://secure.gravatar.com/avatar/#{hash}.png?s=#{size}"
 end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<article id="<%= dom_id comment %>" class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <%= image_tag avatar_url_for(comment.user, size: 64) %>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= link_to comment.user.name, comment.user %></strong>
        <br>
        <%= comment.body %>
        <br>
        <small><%= pluralize(comment.likes.count, 'like') %> · <%= time_ago_in_words(comment.created_at) %> ago</small>
        <br>
        <small><%= render partial: 'likes/like', locals: { likeable: comment } %></small>
      </p>
    </div>
  </div>
</article>

app/views/comments/_form.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <%= image_tag avatar_url_for(current_user, size: 64) %>
    </p>
  </figure>
  <div class="media-content">
  <%= form_with(model: comment) do |form| %>
    <div class="field">
      <p class="control">
        <%= form.text_area :body, class: "textarea", placeholder: "Add a comment ..." %>
      </p>
    </div>
    <nav class="level">
      <div class="level-left">
        <div class="level-item">
          <%= hidden_field_tag 'comment[commentable_id]', commentable.id %>
          <%= hidden_field_tag 'comment[commentable_type]', commentable.class.to_s %>
          <%= form.submit "Submit", class: "button is-info" %>
        </div>
      </div>
    </nav>
    <% end %>
  </div>
</article>

app/views/likes/_like.html.erb
<% like = current_user.likes.find_by(likeable: likeable) %>
<% if like.nil? %>
  <%= link_to "Like", likes_path(like: {likeable_id: likeable.id, likeable_type: likeable.class.to_s }), data: { "turbo-method": :post } %>
<% else %>
  <%= link_to "Unlike", like_path(like), data: { "turbo-method": :delete } %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article id="<%= dom_id post %>" class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <%= image_tag avatar_url_for(post.user, size: 64) %>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= link_to post.user.name, post.user %></strong>
        <br>
        <%= post.body %>
        <br>
        <small><%= pluralize(post.likes.count, 'like') %> · <%= pluralize(post.comments.count, 'comment') %>  · <%= time_ago_in_words(post.created_at) %> ago</small>
        <br>
        <small><%= render partial: 'likes/like', locals: { likeable: post } %> · <%= link_to "Reply", post %></small>
      </p>
    </div>
  </div>
</article>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Timeline</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>Post</h1>
<%= render @post %>

<h2>Comments</h2>

<% @post.comments.each do |comment| %>
<%= render comment %>
<% end %>

<%= render "comments/form", comment: @comment, commentable: @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/profiles/edit.html.erb
<h1>Edit Profile</h1>

<%= form_with(model: @profile) do |form| %>
  <% if @profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% @profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name, class: "label" %>
    <div class="control">
      <%= form.text_field :name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :description, class: "label" %>
    <div class="control">
      <%= form.text_area :description, class: "textarea" %>
    </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= form.submit "Submit", class: "button is-link" %>
    </div>
    <div class="control">
      <%= link_to 'Cancel', url_for(:back), class: "button is-link is-light" %>
    </div>
  </div>
<% end %>