config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'profiles/edit'
  get 'profiles/update'

  get 'friends/destroy'
  devise_for :users, :controllers => { registrations: "my_registrations", omniauth_callbacks: 'users/omniauth_callbacks' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"
  resources :users, only: [:show]
  get 'profile', to: 'users#show'
  resources :friend_requests
  resources :friends, only: [:index, :destroy]
  resources :posts
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resource :profile, only: %i[edit update]
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_default_profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github]
  
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :posts, dependent: :destroy

  has_many :likes
  has_many :comments

  has_one :profile, dependent: :destroy

  def create_default_profile
    create_profile(name: email, description: "Nothing here yet!")
  end

  def remove_friend(friend)
    current_user.friends.destroy(friend)
  end

  def name
    if profile
      profile.name || email
    else
      email
    end
  end

  def is_friend_or_pending_friend(user)
    pending_friends.include?(user) || friends.include?(user) || self == user
  end
  
  def is_friends_with?(friend)
    pending_friends.include?(friend)
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    puts data
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
        user = User.create(
           email: data['email'],
           password: Devise.friendly_token[0,20]
        )
    end
    user
end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Github'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.github_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = params[:id] ? User.find(params[:id]) : current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<figure class="image is-128x128">
  <%= image_tag avatar_url_for(current_user, size: 128), class: "is-rounded" %>
</figure>

<h1><%= @user.name %></h1>
<p><%= @user.profile.description %></p>

<% if @user == current_user %>
<%= link_to "Edit profile", edit_profile_path, class: "button is-link" %>
<% end %>

<% unless @user == current_user || current_user.friends.include?(@user) %>
  <% unless current_user.pending_friends.include?(@user) %>
    <%= link_to "Send friend request", friend_requests_path(friend_id: @user.id), data: {turbo_method: :post } %>
  <% else %>
    <%= link_to "Withdraw friend request", friend_request_path(FriendRequest.find_by(friend_id: @user.id).id), data: {turbo_method: :delete } %>
  <% end %>
<% end %>

<h2>Posts</h2>

<% @user.posts.each do |post| %>
  <%= render post %>
<% end %>