config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'profiles/edit'
  get 'profiles/update'

  get 'friends/destroy'
  devise_for :users, :controllers => { registrations: "my_registrations", omniauth_callbacks: 'users/omniauth_callbacks' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"
  resources :users, only: [:show]
  get 'profile', to: 'users#show'
  resources :friend_requests
  resources :friends, only: [:index, :destroy]
  resources :posts
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]
  resource :profile, only: %i[edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true

  has_many :likes, as: :likeable
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :user_id, uniqueness: { scope: :friend_id, message: "A friend request is already pending"}

  def accept
    user.friends << friend
    destroy
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  after_create :create_inverse_relationship
  after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validate :not_self

  def create_inverse_relationship
    friend.friendships.create(friend: user) if friend.friendships.where(friend: user).blank?
    puts 'test'
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end

  private

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  validates :user_id, uniqueness: { scope: %i[likeable_id likeable_type]}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes, as: :likeable
  has_many :comments, as: :commentable

  scope :posts_by_user, ->(user) { where(user: user)}
  scope :posts_by_friends, ->(user) { where(user: user.friends )}

  scope :timeline_for, ->(user) { posts_by_user(user).or(posts_by_friends(user)) }
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :name,        presence: true
  validates :description, presence: true, length: { maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_default_profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github]
  
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :posts, dependent: :destroy

  has_many :likes
  has_many :comments

  has_one :profile, dependent: :destroy

  def create_default_profile
    create_profile(name: email, description: "Nothing here yet!")
  end

  def remove_friend(friend)
    current_user.friends.destroy(friend)
  end

  def name
    if profile
      profile.name || email
    else
      email
    end
  end

  def is_friend_or_pending_friend(user)
    pending_friends.include?(user) || friends.include?(user) || self == user
  end
  
  def is_friends_with?(friend)
    pending_friends.include?(friend)
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    puts data
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
        user = User.create(
           email: data['email'],
           password: Devise.friendly_token[0,20]
        )
    end
    user
end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: :destroy
  
  def index
    @friends = current_user.friends
  end

  def destroy
    current_user.remove_friend(@friend)
    head :no_content
  end

  def set_friend
    @friend = current_user.friends.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.new(like_params)

    @like.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def like_params
    params.require(:like).permit(:likeable_id, :likeable_type)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.timeline_for(current_user)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = params[:id] ? User.find(params[:id]) : current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url_for(user, opts = {})
    size = opts[:size || 32]

    hash = Digest::MD5.hexdigest(user.email.downcase)
    "https://secure.gravatar.com/avatar/#{hash}.png?s=#{size}"
 end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <h1 class="title">Facebook</h1>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item" %>

      <%= link_to "Timeline", posts_path, class: "navbar-item" %>

      <%= link_to "Friends", friends_path, class: "navbar-item" %>
    </div>

    <div class="navbar-end">
      <% if current_user %>
        <%= link_to current_user.name, current_user, class: "navbar-item" %>
      <% end %>
      <div class="navbar-item">
        <div class="buttons">
          <% if current_user %>
              <%= render "layouts/notifications" %>
              <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete }, class: 'button' %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, class: 'button is-primary has-text-weight-bold' %>
              <%= link_to "Login", new_user_session_path, class: 'button' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<div class="dropdown is-right is-hoverable">
  <div class="dropdown-trigger">
    <button class="button is-link is-inverted" aria-haspopup="true" aria-controls="dropdown-menu2">
    <span>Notifications</span>
      <span class="icon is-small">
        <i class="fas fa-bell"></i>
      </span>
    </button>
  </div>
  <div class="dropdown-menu" id="dropdown-menu2" role="menu">
    <div class="dropdown-content">
      <div class="dropdown-item">
        
        <%= turbo_frame_tag "notifications", src: friend_requests_path do %>
          Some content
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <section class="section">
      <div class="container">
        <div class="content">
          <%= yield %>
        </div>
      </div>
    </section>
  </body>
</html>